print("Getting to know you!")

name = input("What's your name?: ")
favouriteFood = input("What's your favourite food?:")
favouriteMusic = input("What's your favourite music?:")
livingPlace = input("Where do you live?: ")

print("You are")
print(name)
print("You're probably hungry for")
print(favouriteFood)
print("and you're definetely getting your groove on to")
print(favouriteMusic)
print("living in the amazing")
print(livingPlace)